# Centralized Stonecutter properties
mod.id = "bobberbegone"
mod.name = "Bobber Begone Next"
mod.group = "net.nu11une"

loomx.loom_version = "1.17-SNAPSHOT"
loomx.loom_remap_plugin = "fabric-loom"

deps.loader = "0.18.4"

library.faststats = "0.30.1"

["26.2"]
deps.minecraft.start = "26.2"
deps.fabric_api = "0.152.1+26.2"
deps.yacl = "3.9.4+26.2-fabric"
deps.modmenu = "20.0.0"

["26.1"]
deps.minecraft.start = "26.1"
deps.minecraft.end = "26.1.2"
deps.fabric_api = "0.155.2+26.1.2"
deps.yacl = "3.9.6+26.1-fabric"
deps.modmenu = "18.0.0"

["1.21.11"]
deps.minecraft.start = "1.21.11"
deps.minecraft.end = "1.21.11"
deps.yacl = "3.8.2+1.21.11-fabric"
deps.modmenu = "17.0.0"

["1.21.9"]
deps.minecraft.start = "1.21.9"
deps.minecraft.end = "1.21.10"
deps.yacl = "3.8.2+1.21.10-fabric"
deps.modmenu = "16.0.1"

["1.21.6"]
deps.minecraft.start = "1.21.6"
deps.minecraft.end = "1.21.8"
deps.yacl = "3.8.2+1.21.6-fabric"
deps.modmenu = "15.0.2"

["1.21.2"]
deps.minecraft.start = "1.21.2"
deps.minecraft.end = "1.21.5"
deps.yacl = "3.8.2+1.21.3-fabric"
deps.modmenu = "12.0.1"

["1.21"]
deps.minecraft.start = "1.21"
deps.minecraft.end = "1.21.1"
deps.fabric_api = "0.102.0+1.21"
deps.yacl = "3.5.0+1.21-fabric"
deps.modmenu = "11.0.0"

["1.20.5"]
deps.minecraft.start = "1.20.5"
deps.minecraft.end = "1.20.6"
deps.fabric_api = "0.97.5+1.20.5"
deps.yacl = "3.4.2+1.20.5-fabric"
deps.modmenu = "10.0.0"

["1.20"]
deps.minecraft.start = "1.20"
deps.minecraft.end = "1.20.4"
deps.fabric_api = "0.83.0+1.20"
deps.yacl = "3.2.2+1.20"
deps.yacl_modrinth = "3.2.2+1.20-fabric"
deps.modmenu = "7.0.0"
